#!/usr/bin/env bash
#
# Release builder. Produces every shippable artifact for the vad project,
# validates each one against a fresh gRPC server, and gates the final
# release on an HTML review page that opens in your browser and waits
# for an explicit ACCEPT click.
#
# Pipeline:
#   1. Sanity: regenerate gRPC clients (scripts/gen-proto.sh), then clean
#      tree, on a known branch. Stale generated code fails the gate before
#      anything builds.
#   2. Tests (test.sh): go vet, unit tests, basic-vad-web integration,
#      pkg-example pipeline, Docker build + tests/e2e + tests/fetch.
#   3. Build artifacts:
#        bin/vad                 — native binary for this host
#        out/amd64/vad           — fat linux/amd64 standalone binary
#        out/arm64/vad           — fat linux/arm64 standalone binary
#        vad:amd64               — slim linux/amd64 container image
#        vad:arm64               — slim linux/arm64 container image
#   4. Validate each artifact: stand it up on a distinct port, run
#      ./tests/validate (Detect + Fetch-per-backend), capture log.
#   5. Aggregate everything into release-logs/<sha>/:
#        metadata.json           — provenance + per-artifact sha256 / size
#        review.html             — generated by release-review at runtime
#        *.log                   — per-step logs
#   6. Open release-review in browser; BLOCK until operator clicks
#      ACCEPT or CANCEL. On CANCEL, exit non-zero with nothing pushed.
#   7. On ACCEPT, write release_decision.log + zip everything into
#      release_<tag>_<sha>.zip.
#   8. With --release: also push multi-arch image to $REGISTRY and
#      create the GitHub release with --generate-notes (uses PR titles
#      since the last tag — no CHANGELOG file needed).
#
# TODO (not yet implemented; track as separate issues):
#   - SBOM + vulnerability scan: `docker scout cves vad:amd64`,
#     `syft sbom vad:amd64 -o spdx-json > sbom-amd64.json`,
#     `grype vad:amd64 --fail-on high`. Add as a step between validate
#     and review; include results in metadata + HTML.
#   - Image signing: cosign + sigstore keyless sign for both per-arch
#     images and the multi-arch manifest. Run after `docker push` in the
#     --release branch; cache signing receipts under release-logs/<sha>/.
#
# Usage:
#   bash release.sh                       # full pipeline, stops after zip
#   bash release.sh --tag v0.2.0          # version label for manifest + GH release
#   bash release.sh --skip-tests          # bypass test.sh (fast iteration)
#   bash release.sh --skip-validate       # bypass per-artifact validation
#   bash release.sh --skip-review         # auto-accept without opening browser
#   bash release.sh --push                # push multi-arch image to $REGISTRY
#   bash release.sh --release --tag vX.Y.Z
#                                         # also git tag + gh release create
#
# Environment:
#   REGISTRY=ghcr.io/accretional/vad      # image repo for --push / --release
#   ARCHES="linux/amd64 linux/arm64"      # which arches to build
#   SKIP_AMD64=1 / SKIP_ARM64=1
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

IMAGE_NAME="vad"
REGISTRY="${REGISTRY:-ghcr.io/accretional/vad}"
BUILDER_NAME="vad-builder"
ARCHES="${ARCHES:-linux/amd64 linux/arm64}"

# Port allocation for per-artifact validation. Picked high enough to avoid
# common dev ports (50051 is the default vad port).
PORT_NATIVE=50100
PORT_FAT_AMD64=50101
PORT_FAT_ARM64=50102
PORT_SLIM_AMD64=50103
PORT_SLIM_ARM64=50104

TAG=""
PUSH=0
RELEASE=0
SKIP_TESTS=0
SKIP_VALIDATE=0
SKIP_REVIEW=0
while [ $# -gt 0 ]; do
    case "$1" in
        --tag) TAG="$2"; shift 2 ;;
        --push) PUSH=1; shift ;;
        --release) RELEASE=1; shift ;;
        --skip-tests) SKIP_TESTS=1; shift ;;
        --skip-validate) SKIP_VALIDATE=1; shift ;;
        --skip-review) SKIP_REVIEW=1; shift ;;
        -h|--help)
            sed -n '1,/^set -uo pipefail/p' "$0" | grep -E '^#' | sed 's/^# //;s/^#$//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# ---- helpers -------------------------------------------------------------

step() { echo ""; echo "=== $* ==="; }
die()  { echo "ERROR: $*" >&2; exit 1; }
nowiso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# sha256_file <path> → hex digest
sha256_file() {
    if command -v sha256sum >/dev/null; then sha256sum "$1" | awk '{print $1}'
    else shasum -a 256 "$1" | awk '{print $1}'; fi
}

# human_size <path> → "1.2M"
human_size() { du -h "$1" | awk '{print $1}'; }

# wait_port <port> <max_seconds>
wait_port() {
    local p="$1" max="$2"
    for _ in $(seq 1 "$max"); do
        nc -z localhost "$p" 2>/dev/null && return 0
        sleep 1
    done
    return 1
}

# Tracks PIDs / container IDs to clean up on any exit.
CLEANUP_PIDS=()
CLEANUP_CONTAINERS=()
cleanup() {
    [ "${#CLEANUP_PIDS[@]}" -gt 0 ] && kill "${CLEANUP_PIDS[@]}" 2>/dev/null || true
    [ "${#CLEANUP_CONTAINERS[@]}" -gt 0 ] && docker rm -f "${CLEANUP_CONTAINERS[@]}" 2>/dev/null || true
}
trap cleanup EXIT

# ---- 1. Sanity ----------------------------------------------------------
step "Sanity checks"

if [ "$RELEASE" = 1 ] && [ -z "$TAG" ]; then
    die "--release requires --tag <vX.Y.Z>"
fi

# Regenerate Go gRPC client + server bindings BEFORE the clean-tree check.
# If stale generated code is checked in, this surfaces it as a dirty-tree
# failure rather than silently shipping yesterday's protocol.
step "Generate gRPC clients (Go)"
bash scripts/gen-proto.sh

# bin/vad is regenerated below by build-native.sh; exclude it from the
# dirty-tree check so an existing rebuild doesn't block a fresh release.
if ! git diff --quiet -- . ':!bin/vad' || ! git diff --cached --quiet -- . ':!bin/vad'; then
    die "working tree is dirty (commit or stash first; could be stale
generated client code — re-check after gen-proto ran):
$(git status --short -- . ':!bin/vad')"
fi

GIT_SHA=$(git rev-parse --short HEAD)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
BUILD_STARTED=$(nowiso)
TAG_LABEL="${TAG:-$GIT_SHA}"
LOG_DIR="release-logs/${TAG_LABEL}"
rm -rf "$LOG_DIR"
mkdir -p "$LOG_DIR"

echo "  branch: $GIT_BRANCH  commit: $GIT_SHA  tag: ${TAG:-<none>}"
echo "  logs:   $LOG_DIR/"

# ---- 2. Tests (before build) --------------------------------------------
if [ "$SKIP_TESTS" = 0 ]; then
    step "Tests (test.sh)"
    LOG="$LOG_DIR/02_tests.log"
    if ! bash test.sh 2>&1 | tee "$LOG"; then
        die "test.sh failed; see $LOG"
    fi
else
    step "Tests skipped (--skip-tests)"
fi

# ---- 3. Build native binary ---------------------------------------------
step "Native build (host)"
LOG="$LOG_DIR/03_native_build.log"
bash build-native.sh 2>&1 | tee "$LOG"

# ---- 4. buildx setup ----------------------------------------------------
step "buildx (docker-container driver)"
if docker buildx inspect "$BUILDER_NAME" >/dev/null 2>&1; then
    docker buildx use "$BUILDER_NAME"
else
    docker buildx create --name "$BUILDER_NAME" --driver docker-container --use
fi
docker buildx inspect --bootstrap >/dev/null

# ---- 5. Per-arch slim containers + fat host binaries --------------------
rm -rf out
mkdir -p out
for arch in $ARCHES; do
    short=$(echo "$arch" | sed 's,linux/,,')
    case "$short" in
        amd64) [ "${SKIP_AMD64:-0}" = 1 ] && { echo "skipping amd64"; continue; } ;;
        arm64) [ "${SKIP_ARM64:-0}" = 1 ] && { echo "skipping arm64"; continue; } ;;
    esac

    step "Slim container: $arch  →  ${IMAGE_NAME}:${short}"
    LOG="$LOG_DIR/05_container_${short}.log"
    docker buildx build --platform "$arch" --target runtime \
        -t "${IMAGE_NAME}:${short}" --load . 2>&1 | tee "$LOG"

    step "Fat standalone binary: $arch  →  out/${short}/vad"
    LOG="$LOG_DIR/05_export_${short}.log"
    mkdir -p "out/${short}"
    docker buildx build --platform "$arch" --target export \
        --output "type=local,dest=out/${short}" . 2>&1 | tee "$LOG"
    chmod +x "out/${short}/vad"
done

# ---- 6. Build validate + release-review ---------------------------------
step "Building validate + release-review (host tooling)"
go build -o "$LOG_DIR/validate"       ./tests/validate 2>&1 | tee -a "$LOG_DIR/06_build_tools.log"
go build -o "$LOG_DIR/release-review" ./cmd/release-review 2>&1 | tee -a "$LOG_DIR/06_build_tools.log"

# ---- 7. Per-artifact validation -----------------------------------------
# Each subroutine starts the server in background, waits, runs validate,
# kills the server, returns 0/1.

# validation results accumulate as a JSON array fragment for metadata.json
VALIDATIONS_JSON=""
add_validation() {
    local name="$1" port="$2" ok="$3" log="$4"
    local sep=""; [ -n "$VALIDATIONS_JSON" ] && sep=","
    VALIDATIONS_JSON="${VALIDATIONS_JSON}${sep}{\"name\":\"${name}\",\"port\":${port},\"ok\":${ok},\"log_path\":\"${log#${LOG_DIR}/}\"}"
}

validate_native() {
    local port="$PORT_NATIVE"
    local log="$LOG_DIR/07_validate_native.log"
    echo "  starting native bin on :$port"
    ./bin/vad -port "$port" > "$log.server" 2>&1 &
    local pid=$!
    CLEANUP_PIDS+=("$pid")
    if ! wait_port "$port" 30; then
        echo "  native: server never came up" | tee -a "$log"
        kill "$pid" 2>/dev/null
        add_validation native "$port" false "$log"; return 1
    fi
    "$LOG_DIR/validate" -addr "localhost:$port" -wait 30s 2>&1 | tee "$log"
    local rc=${PIPESTATUS[0]}
    kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null || true
    if [ "$rc" = 0 ]; then add_validation native "$port" true  "$log"
    else                   add_validation native "$port" false "$log"; return 1
    fi
}

validate_fat_in_debian() {
    local arch="$1" port="$2"  # arch ∈ {amd64, arm64}
    local log="$LOG_DIR/07_validate_fat_${arch}.log"
    local cname="vad-rel-fat-${arch}"
    local img="vad-rel-fat-${arch}:test"

    echo "  building debian-slim wrapper for fat ${arch} binary"
    local tmp; tmp=$(mktemp -d)
    cp "out/${arch}/vad" "$tmp/"
    cat > "$tmp/Dockerfile" <<EOF
FROM debian:bookworm-slim
COPY vad /vad
ENTRYPOINT ["/vad"]
EOF
    docker build --platform "linux/${arch}" -t "$img" "$tmp" >> "$log.build" 2>&1
    local rc=$?
    rm -rf "$tmp"
    [ "$rc" -ne 0 ] && { add_validation "fat-${arch}" "$port" false "$log"; return 1; }

    echo "  starting fat ${arch} binary in debian on :$port"
    docker run --rm -d --name "$cname" --platform "linux/${arch}" -p "$port:50051" "$img" >/dev/null 2>&1
    CLEANUP_CONTAINERS+=("$cname")
    if ! wait_port "$port" 30; then
        echo "  fat-${arch}: server never came up" | tee -a "$log"
        docker rm -f "$cname" >/dev/null 2>&1
        add_validation "fat-${arch}" "$port" false "$log"; return 1
    fi
    "$LOG_DIR/validate" -addr "localhost:$port" -wait 30s 2>&1 | tee "$log"
    rc=${PIPESTATUS[0]}
    docker rm -f "$cname" >/dev/null 2>&1
    docker rmi "$img" >/dev/null 2>&1
    if [ "$rc" = 0 ]; then add_validation "fat-${arch}" "$port" true  "$log"
    else                   add_validation "fat-${arch}" "$port" false "$log"; return 1
    fi
}

validate_slim_container() {
    local arch="$1" port="$2"
    local log="$LOG_DIR/07_validate_slim_${arch}.log"
    local cname="vad-rel-slim-${arch}"

    echo "  starting slim ${arch} container on :$port"
    docker run --rm -d --name "$cname" --platform "linux/${arch}" -p "$port:50051" "${IMAGE_NAME}:${arch}" >/dev/null 2>&1
    CLEANUP_CONTAINERS+=("$cname")
    if ! wait_port "$port" 30; then
        echo "  slim-${arch}: server never came up" | tee -a "$log"
        docker logs "$cname" 2>&1 | tail -20 | tee -a "$log"
        docker rm -f "$cname" >/dev/null 2>&1
        add_validation "slim-${arch}" "$port" false "$log"; return 1
    fi
    "$LOG_DIR/validate" -addr "localhost:$port" -wait 30s 2>&1 | tee "$log"
    local rc=${PIPESTATUS[0]}
    docker rm -f "$cname" >/dev/null 2>&1
    if [ "$rc" = 0 ]; then add_validation "slim-${arch}" "$port" true  "$log"
    else                   add_validation "slim-${arch}" "$port" false "$log"; return 1
    fi
}

if [ "$SKIP_VALIDATE" = 0 ]; then
    step "Validation: native binary"
    validate_native || echo "  (native validation FAILED — review log)"

    for arch in amd64 arm64; do
        case "$arch" in
            amd64) port=$PORT_FAT_AMD64 ;;
            arm64) port=$PORT_FAT_ARM64 ;;
        esac
        step "Validation: fat ${arch} binary in debian-slim"
        validate_fat_in_debian "$arch" "$port" || echo "  (fat-${arch} validation FAILED — review log)"
    done

    for arch in amd64 arm64; do
        case "$arch" in
            amd64) port=$PORT_SLIM_AMD64 ;;
            arm64) port=$PORT_SLIM_ARM64 ;;
        esac
        step "Validation: slim ${arch} container"
        validate_slim_container "$arch" "$port" || echo "  (slim-${arch} validation FAILED — review log)"
    done
else
    step "Validation skipped (--skip-validate)"
fi

# TODO: SBOM + vulnerability scan goes HERE.
# Run something like:
#   docker scout cves vad:amd64 --output "$LOG_DIR/08_scout_amd64.json"
#   syft scan docker:vad:amd64 -o spdx-json=$LOG_DIR/08_sbom_amd64.spdx.json
#   grype vad:amd64 --fail-on high -o json=$LOG_DIR/08_grype_amd64.json
# Then surface counts in the review HTML.

# ---- 8. Assemble metadata + artifact manifest ---------------------------
step "Aggregating release-logs/${TAG_LABEL}/"

# Artifact rows: file path | name | size | sha256
build_artifact_row() {
    local name="$1" path="$2"
    [ ! -f "$path" ] && return
    printf '{"name":"%s","path":"%s","size":"%s","sha256":"%s"}' \
        "$name" "$path" "$(human_size "$path")" "$(sha256_file "$path")"
}

ARTIFACTS_JSON="$(build_artifact_row 'native (host)'   bin/vad)"
for arch in amd64 arm64; do
    f="out/${arch}/vad"
    [ -f "$f" ] && ARTIFACTS_JSON="${ARTIFACTS_JSON},$(build_artifact_row "fat-${arch} (linux/${arch})" "$f")"
done

# Image digests
IMG_DIGESTS=""
for arch in amd64 arm64; do
    img="${IMAGE_NAME}:${arch}"
    if digest=$(docker image inspect -f '{{.Id}}' "$img" 2>/dev/null); then
        sep=""; [ -n "$IMG_DIGESTS" ] && sep=","
        size=$(docker images --format '{{.Size}}' "$img" | head -1)
        IMG_DIGESTS="${IMG_DIGESTS}${sep}{\"name\":\"image: ${img}\",\"path\":\"${img}\",\"size\":\"${size}\",\"sha256\":\"${digest##sha256:}\"}"
    fi
done
[ -n "$IMG_DIGESTS" ] && ARTIFACTS_JSON="${ARTIFACTS_JSON},${IMG_DIGESTS}"

# Log file list (everything ending in .log in $LOG_DIR)
LOGS_JSON=""
for f in "$LOG_DIR"/*.log; do
    [ ! -f "$f" ] && continue
    base=$(basename "$f")
    sep=""; [ -n "$LOGS_JSON" ] && sep=","
    LOGS_JSON="${LOGS_JSON}${sep}{\"name\":\"${base}\",\"path\":\"${base}\"}"
done

cat > "$LOG_DIR/metadata.json" <<EOF
{
  "tag":           "${TAG_LABEL}",
  "git_sha":       "${GIT_SHA}",
  "git_branch":    "${GIT_BRANCH}",
  "date":          "$(nowiso)",
  "build_host":    "$(hostname -s)",
  "build_os_arch": "$(uname -s)/$(uname -m)",
  "build_user":    "${USER:-unknown}",
  "build_started": "${BUILD_STARTED}",
  "artifacts":     [${ARTIFACTS_JSON}],
  "validations":   [${VALIDATIONS_JSON}],
  "logs":          [${LOGS_JSON}]
}
EOF

# ---- 9. Review gate -----------------------------------------------------
if [ "$SKIP_REVIEW" = 0 ]; then
    step "Opening release review (browser; waiting for ACCEPT)"
    if ! "$LOG_DIR/release-review" -logs "$LOG_DIR"; then
        echo "  CANCELLED. Nothing pushed. release-logs/${TAG_LABEL}/ preserved."
        exit 1
    fi
else
    step "Review skipped (--skip-review) — proceeding as if ACCEPTED"
fi

echo "release ACCEPTED at $(nowiso)" > "$LOG_DIR/release_decision.log"
echo "validations: $(echo "$VALIDATIONS_JSON" | tr ',' '\n' | grep -c '"ok":true') OK / $(echo "$VALIDATIONS_JSON" | tr ',' '\n' | grep -c '"ok":false') FAIL" >> "$LOG_DIR/release_decision.log"

# ---- 10. Zip the release bundle ----------------------------------------
step "Building release zip"
ZIP_NAME="release_${TAG_LABEL}_${GIT_SHA}.zip"
rm -f "$ZIP_NAME"
# Include logs + the on-disk binary artifacts (not the container images;
# those live in the registry once pushed).
zip -qr "$ZIP_NAME" "$LOG_DIR" bin/vad out/
echo "  built: $ZIP_NAME ($(human_size "$ZIP_NAME"))"

# ---- 11. Push (multi-arch manifest) ------------------------------------
if [ "$PUSH" = 1 ]; then
    step "Push multi-arch manifest to $REGISTRY"
    MANIFEST_TAG="${REGISTRY}:${TAG_LABEL}"
    LATEST_TAG="${REGISTRY}:latest"
    docker buildx build --platform "$(echo "$ARCHES" | tr ' ' ',')" --target runtime \
        -t "$MANIFEST_TAG" -t "$LATEST_TAG" --push . 2>&1 | tee "$LOG_DIR/11_push.log"
    echo "  pushed: $MANIFEST_TAG and $LATEST_TAG"
fi

# TODO: cosign sign goes HERE (after push):
#   cosign sign --yes "$MANIFEST_TAG"
#   cosign sign --yes "$LATEST_TAG"
# Log receipts to $LOG_DIR/12_cosign.log.

# ---- 12. GitHub release ------------------------------------------------
if [ "$RELEASE" = 1 ]; then
    step "GitHub release ${TAG}"
    if git rev-parse "$TAG" >/dev/null 2>&1; then
        echo "  tag $TAG already exists; skipping git tag"
    else
        git tag -a "$TAG" -m "Release $TAG"
        git push origin "$TAG"
    fi
    if command -v gh >/dev/null; then
        gh release create "$TAG" \
            --title "$TAG" \
            --generate-notes \
            "$ZIP_NAME" bin/vad out/amd64/vad out/arm64/vad
        echo "  created: gh release $TAG"
    else
        echo "  gh CLI not installed — skipping release creation."
        echo "  Manual upload: $ZIP_NAME plus the binaries."
    fi
fi

# ---- summary ----------------------------------------------------------
echo ""
echo "=== Release artifacts (${TAG_LABEL}) ==="
echo "Native:"
echo "  bin/vad                       $(human_size bin/vad)"
echo "Standalone Linux binaries:"
for f in out/*/vad; do [ -f "$f" ] && echo "  $f                $(human_size $f)"; done
echo "Slim runtime containers:"
docker images "${IMAGE_NAME}" --format "  {{.Repository}}:{{.Tag}}  {{.Size}}"
echo "Zip:    $ZIP_NAME ($(human_size "$ZIP_NAME"))"
echo "Logs:   $LOG_DIR/"
echo ""
echo "OK"
