// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: vad.proto

package vadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audio contains raw PCM audio data for voice activity detection.
type Audio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio samples as 16kHz mono float32 little-endian bytes.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz. Must be 16000.
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_vad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{0}
}

func (x *Audio) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Audio) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Diarization contains the detected speaker segments.
type Diarization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The detected speech segments with speaker assignments.
	Segments []*Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Total duration of the input audio in seconds.
	Duration      float64 `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diarization) Reset() {
	*x = Diarization{}
	mi := &file_vad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diarization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diarization) ProtoMessage() {}

func (x *Diarization) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diarization.ProtoReflect.Descriptor instead.
func (*Diarization) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{1}
}

func (x *Diarization) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Diarization) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// Segment represents a contiguous speech region attributed to a single speaker.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time in seconds from the beginning of the audio.
	Start float64 `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	// End time in seconds from the beginning of the audio.
	End float64 `protobuf:"fixed64,2,opt,name=end,proto3" json:"end,omitempty"`
	// Speaker identifier (0-indexed).
	SpeakerId int32 `protobuf:"varint,3,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`
	// Confidence score for this segment (0.0 - 1.0).
	Confidence    float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_vad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Segment) GetSpeakerId() int32 {
	if x != nil {
		return x.SpeakerId
	}
	return 0
}

func (x *Segment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// AudioChunk is one piece of an ongoing audio stream sent to DetectStream.
type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio samples as 16 kHz mono float32 little-endian bytes.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz. Must be 16000. Send on the first chunk; the server
	// requires it to match across all chunks in a stream.
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Hint that no more audio is coming. The server SHOULD flush any pending
	// segments and emit a final SpeechActivity{speech_active=false} event before
	// closing its half of the stream. Client should still half-close its send
	// direction (CloseSend) after sending this chunk.
	EndOfStream   bool `protobuf:"varint,3,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_vad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{3}
}

func (x *AudioChunk) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

// SegmentationEvent is one streamed event emitted by DetectStream.
type SegmentationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in seconds from the start of the stream that this event refers
	// to (e.g., the transition time for an activity event, or the end time of a
	// completed segment).
	Timestamp float64 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SegmentationEvent_Activity
	//	*SegmentationEvent_Segment
	Event         isSegmentationEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentationEvent) Reset() {
	*x = SegmentationEvent{}
	mi := &file_vad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentationEvent) ProtoMessage() {}

func (x *SegmentationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentationEvent.ProtoReflect.Descriptor instead.
func (*SegmentationEvent) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentationEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SegmentationEvent) GetEvent() isSegmentationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SegmentationEvent) GetActivity() *SpeechActivity {
	if x != nil {
		if x, ok := x.Event.(*SegmentationEvent_Activity); ok {
			return x.Activity
		}
	}
	return nil
}

func (x *SegmentationEvent) GetSegment() *Segment {
	if x != nil {
		if x, ok := x.Event.(*SegmentationEvent_Segment); ok {
			return x.Segment
		}
	}
	return nil
}

type isSegmentationEvent_Event interface {
	isSegmentationEvent_Event()
}

type SegmentationEvent_Activity struct {
	// Speech activity transition — someone started or stopped speaking.
	// Emitted hot, as soon as the rolling analysis detects a state change.
	Activity *SpeechActivity `protobuf:"bytes,2,opt,name=activity,proto3,oneof"`
}

type SegmentationEvent_Segment struct {
	// A completed speech region. Emitted after the region has ended and the
	// backend has finalized it; useful for downstream diarization or logging.
	Segment *Segment `protobuf:"bytes,3,opt,name=segment,proto3,oneof"`
}

func (*SegmentationEvent_Activity) isSegmentationEvent_Event() {}

func (*SegmentationEvent_Segment) isSegmentationEvent_Event() {}

// SpeechActivity is a transition event in DetectStream.
type SpeechActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if speech started at `timestamp`; false if it stopped.
	SpeechActive  bool `protobuf:"varint,1,opt,name=speech_active,json=speechActive,proto3" json:"speech_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechActivity) Reset() {
	*x = SpeechActivity{}
	mi := &file_vad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechActivity) ProtoMessage() {}

func (x *SpeechActivity) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechActivity.ProtoReflect.Descriptor instead.
func (*SpeechActivity) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{5}
}

func (x *SpeechActivity) GetSpeechActive() bool {
	if x != nil {
		return x.SpeechActive
	}
	return false
}

// FetchRequest requests the ONNX model weights.
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_vad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{6}
}

// FetchResponse returns model weights either directly or as a URL.
type FetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FetchResponse_Weights
	//	*FetchResponse_Url
	Result        isFetchResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_vad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{7}
}

func (x *FetchResponse) GetResult() isFetchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FetchResponse) GetWeights() []byte {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Weights); ok {
			return x.Weights
		}
	}
	return nil
}

func (x *FetchResponse) GetUrl() string {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Url); ok {
			return x.Url
		}
	}
	return ""
}

type isFetchResponse_Result interface {
	isFetchResponse_Result()
}

type FetchResponse_Weights struct {
	// The raw ONNX model bytes.
	Weights []byte `protobuf:"bytes,1,opt,name=weights,proto3,oneof"`
}

type FetchResponse_Url struct {
	// A URL where the model can be downloaded.
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*FetchResponse_Weights) isFetchResponse_Result() {}

func (*FetchResponse_Url) isFetchResponse_Result() {}

var File_vad_proto protoreflect.FileDescriptor

const file_vad_proto_rawDesc = "" +
	"\n" +
	"\tvad.proto\x12\x03vad\"B\n" +
	"\x05Audio\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"S\n" +
	"\vDiarization\x12(\n" +
	"\bsegments\x18\x01 \x03(\v2\f.vad.SegmentR\bsegments\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\"p\n" +
	"\aSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x01R\x03end\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x03 \x01(\x05R\tspeakerId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"k\n" +
	"\n" +
	"AudioChunk\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\"\n" +
	"\rend_of_stream\x18\x03 \x01(\bR\vendOfStream\"\x97\x01\n" +
	"\x11SegmentationEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x121\n" +
	"\bactivity\x18\x02 \x01(\v2\x13.vad.SpeechActivityH\x00R\bactivity\x12(\n" +
	"\asegment\x18\x03 \x01(\v2\f.vad.SegmentH\x00R\asegmentB\a\n" +
	"\x05event\"5\n" +
	"\x0eSpeechActivity\x12#\n" +
	"\rspeech_active\x18\x01 \x01(\bR\fspeechActive\"\x0e\n" +
	"\fFetchRequest\"I\n" +
	"\rFetchResponse\x12\x1a\n" +
	"\aweights\x18\x01 \x01(\fH\x00R\aweights\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03urlB\b\n" +
	"\x06result2\xa8\x01\n" +
	"\x11VoiceSegmentation\x12&\n" +
	"\x06Detect\x12\n" +
	".vad.Audio\x1a\x10.vad.Diarization\x12;\n" +
	"\fDetectStream\x12\x0f.vad.AudioChunk\x1a\x16.vad.SegmentationEvent(\x010\x01\x12.\n" +
	"\x05Fetch\x12\x11.vad.FetchRequest\x1a\x12.vad.FetchResponseB(Z&github.com/accretional/vad/proto/vadpbb\x06proto3"

var (
	file_vad_proto_rawDescOnce sync.Once
	file_vad_proto_rawDescData []byte
)

func file_vad_proto_rawDescGZIP() []byte {
	file_vad_proto_rawDescOnce.Do(func() {
		file_vad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)))
	})
	return file_vad_proto_rawDescData
}

var file_vad_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vad_proto_goTypes = []any{
	(*Audio)(nil),             // 0: vad.Audio
	(*Diarization)(nil),       // 1: vad.Diarization
	(*Segment)(nil),           // 2: vad.Segment
	(*AudioChunk)(nil),        // 3: vad.AudioChunk
	(*SegmentationEvent)(nil), // 4: vad.SegmentationEvent
	(*SpeechActivity)(nil),    // 5: vad.SpeechActivity
	(*FetchRequest)(nil),      // 6: vad.FetchRequest
	(*FetchResponse)(nil),     // 7: vad.FetchResponse
}
var file_vad_proto_depIdxs = []int32{
	2, // 0: vad.Diarization.segments:type_name -> vad.Segment
	5, // 1: vad.SegmentationEvent.activity:type_name -> vad.SpeechActivity
	2, // 2: vad.SegmentationEvent.segment:type_name -> vad.Segment
	0, // 3: vad.VoiceSegmentation.Detect:input_type -> vad.Audio
	3, // 4: vad.VoiceSegmentation.DetectStream:input_type -> vad.AudioChunk
	6, // 5: vad.VoiceSegmentation.Fetch:input_type -> vad.FetchRequest
	1, // 6: vad.VoiceSegmentation.Detect:output_type -> vad.Diarization
	4, // 7: vad.VoiceSegmentation.DetectStream:output_type -> vad.SegmentationEvent
	7, // 8: vad.VoiceSegmentation.Fetch:output_type -> vad.FetchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vad_proto_init() }
func file_vad_proto_init() {
	if File_vad_proto != nil {
		return
	}
	file_vad_proto_msgTypes[4].OneofWrappers = []any{
		(*SegmentationEvent_Activity)(nil),
		(*SegmentationEvent_Segment)(nil),
	}
	file_vad_proto_msgTypes[7].OneofWrappers = []any{
		(*FetchResponse_Weights)(nil),
		(*FetchResponse_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vad_proto_goTypes,
		DependencyIndexes: file_vad_proto_depIdxs,
		MessageInfos:      file_vad_proto_msgTypes,
	}.Build()
	File_vad_proto = out.File
	file_vad_proto_goTypes = nil
	file_vad_proto_depIdxs = nil
}
