// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: vad.proto

package vadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audio contains raw PCM audio data for voice activity detection.
type Audio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio samples as 16kHz mono float32 little-endian bytes.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz. Must be 16000.
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_vad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{0}
}

func (x *Audio) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Audio) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Diarization contains the detected speaker segments.
type Diarization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The detected speech segments with speaker assignments.
	Segments []*Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Total duration of the input audio in seconds.
	Duration      float64 `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diarization) Reset() {
	*x = Diarization{}
	mi := &file_vad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diarization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diarization) ProtoMessage() {}

func (x *Diarization) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diarization.ProtoReflect.Descriptor instead.
func (*Diarization) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{1}
}

func (x *Diarization) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Diarization) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// Segment represents a contiguous speech region attributed to a single speaker.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time in seconds from the beginning of the audio.
	Start float64 `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	// End time in seconds from the beginning of the audio.
	End float64 `protobuf:"fixed64,2,opt,name=end,proto3" json:"end,omitempty"`
	// Speaker identifier (0-indexed).
	SpeakerId int32 `protobuf:"varint,3,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`
	// Confidence score for this segment (0.0 - 1.0).
	Confidence    float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_vad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Segment) GetSpeakerId() int32 {
	if x != nil {
		return x.SpeakerId
	}
	return 0
}

func (x *Segment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_vad_proto protoreflect.FileDescriptor

const file_vad_proto_rawDesc = "" +
	"\n" +
	"\tvad.proto\x12\x03vad\"B\n" +
	"\x05Audio\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"S\n" +
	"\vDiarization\x12(\n" +
	"\bsegments\x18\x01 \x03(\v2\f.vad.SegmentR\bsegments\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\"p\n" +
	"\aSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x01R\x03end\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x03 \x01(\x05R\tspeakerId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence2;\n" +
	"\x11VoiceSegmentation\x12&\n" +
	"\x06Detect\x12\n" +
	".vad.Audio\x1a\x10.vad.DiarizationB(Z&github.com/accretional/vad/proto/vadpbb\x06proto3"

var (
	file_vad_proto_rawDescOnce sync.Once
	file_vad_proto_rawDescData []byte
)

func file_vad_proto_rawDescGZIP() []byte {
	file_vad_proto_rawDescOnce.Do(func() {
		file_vad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)))
	})
	return file_vad_proto_rawDescData
}

var file_vad_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vad_proto_goTypes = []any{
	(*Audio)(nil),       // 0: vad.Audio
	(*Diarization)(nil), // 1: vad.Diarization
	(*Segment)(nil),     // 2: vad.Segment
}
var file_vad_proto_depIdxs = []int32{
	2, // 0: vad.Diarization.segments:type_name -> vad.Segment
	0, // 1: vad.VoiceSegmentation.Detect:input_type -> vad.Audio
	1, // 2: vad.VoiceSegmentation.Detect:output_type -> vad.Diarization
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vad_proto_init() }
func file_vad_proto_init() {
	if File_vad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vad_proto_goTypes,
		DependencyIndexes: file_vad_proto_depIdxs,
		MessageInfos:      file_vad_proto_msgTypes,
	}.Build()
	File_vad_proto = out.File
	file_vad_proto_goTypes = nil
	file_vad_proto_depIdxs = nil
}
