// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: vad.proto

package vadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VADModel selects which backend implementation the server loads at startup.
// Wire values are stable; new entries must append at the next free number.
type VADModel int32

const (
	VADModel_VAD_MODEL_UNSPECIFIED VADModel = 0
	// Pyannote Segmentation 3.0 — full diarization, 3 speakers max.
	VADModel_VAD_MODEL_PYANNOTE VADModel = 1
	// FunASR FSMN-VAD — tiny, VAD-only, Chinese-trained (works on EN, validate).
	VADModel_VAD_MODEL_FSMN VADModel = 2
	// FireRedTeam DFSMN-VAD — small, VAD-only, English-friendly.
	VADModel_VAD_MODEL_FIRERED VADModel = 3
	// NVIDIA Frame_VAD_Multilingual_MarbleNet_v2.0 — multilingual.
	VADModel_VAD_MODEL_MARBLENET VADModel = 4
	// Silero VAD — well-known tiny model.
	VADModel_VAD_MODEL_SILERO VADModel = 5
)

// Enum value maps for VADModel.
var (
	VADModel_name = map[int32]string{
		0: "VAD_MODEL_UNSPECIFIED",
		1: "VAD_MODEL_PYANNOTE",
		2: "VAD_MODEL_FSMN",
		3: "VAD_MODEL_FIRERED",
		4: "VAD_MODEL_MARBLENET",
		5: "VAD_MODEL_SILERO",
	}
	VADModel_value = map[string]int32{
		"VAD_MODEL_UNSPECIFIED": 0,
		"VAD_MODEL_PYANNOTE":    1,
		"VAD_MODEL_FSMN":        2,
		"VAD_MODEL_FIRERED":     3,
		"VAD_MODEL_MARBLENET":   4,
		"VAD_MODEL_SILERO":      5,
	}
)

func (x VADModel) Enum() *VADModel {
	p := new(VADModel)
	*p = x
	return p
}

func (x VADModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VADModel) Descriptor() protoreflect.EnumDescriptor {
	return file_vad_proto_enumTypes[0].Descriptor()
}

func (VADModel) Type() protoreflect.EnumType {
	return &file_vad_proto_enumTypes[0]
}

func (x VADModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VADModel.Descriptor instead.
func (VADModel) EnumDescriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{0}
}

// Audio contains raw PCM audio data for voice activity detection.
type Audio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio samples as 16kHz mono float32 little-endian bytes.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz. Must be 16000.
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_vad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{0}
}

func (x *Audio) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Audio) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Diarization contains the detected speaker segments.
type Diarization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The detected speech segments with speaker assignments.
	Segments []*Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Total duration of the input audio in seconds.
	Duration      float64 `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diarization) Reset() {
	*x = Diarization{}
	mi := &file_vad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diarization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diarization) ProtoMessage() {}

func (x *Diarization) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diarization.ProtoReflect.Descriptor instead.
func (*Diarization) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{1}
}

func (x *Diarization) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Diarization) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// Segment represents a contiguous speech region attributed to a single speaker.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time in seconds from the beginning of the audio.
	Start float64 `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	// End time in seconds from the beginning of the audio.
	End float64 `protobuf:"fixed64,2,opt,name=end,proto3" json:"end,omitempty"`
	// Speaker identifier (0-indexed).
	SpeakerId int32 `protobuf:"varint,3,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`
	// Confidence score for this segment (0.0 - 1.0).
	Confidence    float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_vad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Segment) GetSpeakerId() int32 {
	if x != nil {
		return x.SpeakerId
	}
	return 0
}

func (x *Segment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// AudioChunk is one piece of an ongoing audio stream sent to DetectStream.
type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio samples as 16 kHz mono float32 little-endian bytes.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz. Must be 16000. Send on the first chunk; the server
	// requires it to match across all chunks in a stream.
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Hint that no more audio is coming. The server SHOULD flush any pending
	// segments and emit a final SpeechActivity{speech_active=false} event before
	// closing its half of the stream. Client should still half-close its send
	// direction (CloseSend) after sending this chunk.
	EndOfStream   bool `protobuf:"varint,3,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_vad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{3}
}

func (x *AudioChunk) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

// SegmentationEvent is one streamed event emitted by DetectStream.
type SegmentationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in seconds from the start of the stream that this event refers
	// to (e.g., the transition time for an activity event, or the end time of a
	// completed segment).
	Timestamp float64 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SegmentationEvent_Activity
	//	*SegmentationEvent_Segment
	Event         isSegmentationEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentationEvent) Reset() {
	*x = SegmentationEvent{}
	mi := &file_vad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentationEvent) ProtoMessage() {}

func (x *SegmentationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentationEvent.ProtoReflect.Descriptor instead.
func (*SegmentationEvent) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentationEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SegmentationEvent) GetEvent() isSegmentationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SegmentationEvent) GetActivity() *SpeechActivity {
	if x != nil {
		if x, ok := x.Event.(*SegmentationEvent_Activity); ok {
			return x.Activity
		}
	}
	return nil
}

func (x *SegmentationEvent) GetSegment() *Segment {
	if x != nil {
		if x, ok := x.Event.(*SegmentationEvent_Segment); ok {
			return x.Segment
		}
	}
	return nil
}

type isSegmentationEvent_Event interface {
	isSegmentationEvent_Event()
}

type SegmentationEvent_Activity struct {
	// Speech activity transition — someone started or stopped speaking.
	// Emitted hot, as soon as the rolling analysis detects a state change.
	Activity *SpeechActivity `protobuf:"bytes,2,opt,name=activity,proto3,oneof"`
}

type SegmentationEvent_Segment struct {
	// A completed speech region. Emitted after the region has ended and the
	// backend has finalized it; useful for downstream diarization or logging.
	Segment *Segment `protobuf:"bytes,3,opt,name=segment,proto3,oneof"`
}

func (*SegmentationEvent_Activity) isSegmentationEvent_Event() {}

func (*SegmentationEvent_Segment) isSegmentationEvent_Event() {}

// SpeechActivity is a transition event in DetectStream.
type SpeechActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if speech started at `timestamp`; false if it stopped.
	SpeechActive  bool `protobuf:"varint,1,opt,name=speech_active,json=speechActive,proto3" json:"speech_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechActivity) Reset() {
	*x = SpeechActivity{}
	mi := &file_vad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechActivity) ProtoMessage() {}

func (x *SpeechActivity) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechActivity.ProtoReflect.Descriptor instead.
func (*SpeechActivity) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{5}
}

func (x *SpeechActivity) GetSpeechActive() bool {
	if x != nil {
		return x.SpeechActive
	}
	return false
}

// VADConfig is the server startup configuration. Provided via the -config
// flag pointing at a textproto file; unset fields fall back to per-model
// defaults documented in cmd/vad/main.go.
type VADConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which backend to load.
	Model VADModel `protobuf:"varint,1,opt,name=model,proto3,enum=vad.VADModel" json:"model,omitempty"`
	// Path to the weights directory (or single ONNX file for pyannote). If
	// empty, a per-model default is used (e.g. weights/fsmn-vad/ for FSMN).
	WeightsDir string `protobuf:"bytes,2,opt,name=weights_dir,json=weightsDir,proto3" json:"weights_dir,omitempty"`
	// gRPC port. Defaults to 50051 if 0.
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// ONNX Runtime shared library path. Falls back to the ONNXRUNTIME_LIB env
	// var if empty.
	OnnxruntimeLib string `protobuf:"bytes,4,opt,name=onnxruntime_lib,json=onnxruntimeLib,proto3" json:"onnxruntime_lib,omitempty"`
	// URL returned by Fetch RPC (only used for pyannote backend; informational
	// for clients fetching weights for transformers.js).
	WeightsUrl    string `protobuf:"bytes,5,opt,name=weights_url,json=weightsUrl,proto3" json:"weights_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VADConfig) Reset() {
	*x = VADConfig{}
	mi := &file_vad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADConfig) ProtoMessage() {}

func (x *VADConfig) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADConfig.ProtoReflect.Descriptor instead.
func (*VADConfig) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{6}
}

func (x *VADConfig) GetModel() VADModel {
	if x != nil {
		return x.Model
	}
	return VADModel_VAD_MODEL_UNSPECIFIED
}

func (x *VADConfig) GetWeightsDir() string {
	if x != nil {
		return x.WeightsDir
	}
	return ""
}

func (x *VADConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VADConfig) GetOnnxruntimeLib() string {
	if x != nil {
		return x.OnnxruntimeLib
	}
	return ""
}

func (x *VADConfig) GetWeightsUrl() string {
	if x != nil {
		return x.WeightsUrl
	}
	return ""
}

// FetchRequest requests the ONNX model weights.
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_vad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{7}
}

// FetchResponse returns model weights either directly or as a URL.
type FetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FetchResponse_Weights
	//	*FetchResponse_Url
	Result        isFetchResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_vad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_vad_proto_rawDescGZIP(), []int{8}
}

func (x *FetchResponse) GetResult() isFetchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FetchResponse) GetWeights() []byte {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Weights); ok {
			return x.Weights
		}
	}
	return nil
}

func (x *FetchResponse) GetUrl() string {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Url); ok {
			return x.Url
		}
	}
	return ""
}

type isFetchResponse_Result interface {
	isFetchResponse_Result()
}

type FetchResponse_Weights struct {
	// The raw ONNX model bytes.
	Weights []byte `protobuf:"bytes,1,opt,name=weights,proto3,oneof"`
}

type FetchResponse_Url struct {
	// A URL where the model can be downloaded.
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*FetchResponse_Weights) isFetchResponse_Result() {}

func (*FetchResponse_Url) isFetchResponse_Result() {}

var File_vad_proto protoreflect.FileDescriptor

const file_vad_proto_rawDesc = "" +
	"\n" +
	"\tvad.proto\x12\x03vad\"B\n" +
	"\x05Audio\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"S\n" +
	"\vDiarization\x12(\n" +
	"\bsegments\x18\x01 \x03(\v2\f.vad.SegmentR\bsegments\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\"p\n" +
	"\aSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x01R\x03end\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x03 \x01(\x05R\tspeakerId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"k\n" +
	"\n" +
	"AudioChunk\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\"\n" +
	"\rend_of_stream\x18\x03 \x01(\bR\vendOfStream\"\x97\x01\n" +
	"\x11SegmentationEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x121\n" +
	"\bactivity\x18\x02 \x01(\v2\x13.vad.SpeechActivityH\x00R\bactivity\x12(\n" +
	"\asegment\x18\x03 \x01(\v2\f.vad.SegmentH\x00R\asegmentB\a\n" +
	"\x05event\"5\n" +
	"\x0eSpeechActivity\x12#\n" +
	"\rspeech_active\x18\x01 \x01(\bR\fspeechActive\"\xaf\x01\n" +
	"\tVADConfig\x12#\n" +
	"\x05model\x18\x01 \x01(\x0e2\r.vad.VADModelR\x05model\x12\x1f\n" +
	"\vweights_dir\x18\x02 \x01(\tR\n" +
	"weightsDir\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12'\n" +
	"\x0fonnxruntime_lib\x18\x04 \x01(\tR\x0eonnxruntimeLib\x12\x1f\n" +
	"\vweights_url\x18\x05 \x01(\tR\n" +
	"weightsUrl\"\x0e\n" +
	"\fFetchRequest\"I\n" +
	"\rFetchResponse\x12\x1a\n" +
	"\aweights\x18\x01 \x01(\fH\x00R\aweights\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03urlB\b\n" +
	"\x06result*\x97\x01\n" +
	"\bVADModel\x12\x19\n" +
	"\x15VAD_MODEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VAD_MODEL_PYANNOTE\x10\x01\x12\x12\n" +
	"\x0eVAD_MODEL_FSMN\x10\x02\x12\x15\n" +
	"\x11VAD_MODEL_FIRERED\x10\x03\x12\x17\n" +
	"\x13VAD_MODEL_MARBLENET\x10\x04\x12\x14\n" +
	"\x10VAD_MODEL_SILERO\x10\x052\xa8\x01\n" +
	"\x11VoiceSegmentation\x12&\n" +
	"\x06Detect\x12\n" +
	".vad.Audio\x1a\x10.vad.Diarization\x12;\n" +
	"\fDetectStream\x12\x0f.vad.AudioChunk\x1a\x16.vad.SegmentationEvent(\x010\x01\x12.\n" +
	"\x05Fetch\x12\x11.vad.FetchRequest\x1a\x12.vad.FetchResponseB(Z&github.com/accretional/vad/proto/vadpbb\x06proto3"

var (
	file_vad_proto_rawDescOnce sync.Once
	file_vad_proto_rawDescData []byte
)

func file_vad_proto_rawDescGZIP() []byte {
	file_vad_proto_rawDescOnce.Do(func() {
		file_vad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)))
	})
	return file_vad_proto_rawDescData
}

var file_vad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vad_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_vad_proto_goTypes = []any{
	(VADModel)(0),             // 0: vad.VADModel
	(*Audio)(nil),             // 1: vad.Audio
	(*Diarization)(nil),       // 2: vad.Diarization
	(*Segment)(nil),           // 3: vad.Segment
	(*AudioChunk)(nil),        // 4: vad.AudioChunk
	(*SegmentationEvent)(nil), // 5: vad.SegmentationEvent
	(*SpeechActivity)(nil),    // 6: vad.SpeechActivity
	(*VADConfig)(nil),         // 7: vad.VADConfig
	(*FetchRequest)(nil),      // 8: vad.FetchRequest
	(*FetchResponse)(nil),     // 9: vad.FetchResponse
}
var file_vad_proto_depIdxs = []int32{
	3, // 0: vad.Diarization.segments:type_name -> vad.Segment
	6, // 1: vad.SegmentationEvent.activity:type_name -> vad.SpeechActivity
	3, // 2: vad.SegmentationEvent.segment:type_name -> vad.Segment
	0, // 3: vad.VADConfig.model:type_name -> vad.VADModel
	1, // 4: vad.VoiceSegmentation.Detect:input_type -> vad.Audio
	4, // 5: vad.VoiceSegmentation.DetectStream:input_type -> vad.AudioChunk
	8, // 6: vad.VoiceSegmentation.Fetch:input_type -> vad.FetchRequest
	2, // 7: vad.VoiceSegmentation.Detect:output_type -> vad.Diarization
	5, // 8: vad.VoiceSegmentation.DetectStream:output_type -> vad.SegmentationEvent
	9, // 9: vad.VoiceSegmentation.Fetch:output_type -> vad.FetchResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vad_proto_init() }
func file_vad_proto_init() {
	if File_vad_proto != nil {
		return
	}
	file_vad_proto_msgTypes[4].OneofWrappers = []any{
		(*SegmentationEvent_Activity)(nil),
		(*SegmentationEvent_Segment)(nil),
	}
	file_vad_proto_msgTypes[8].OneofWrappers = []any{
		(*FetchResponse_Weights)(nil),
		(*FetchResponse_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vad_proto_rawDesc), len(file_vad_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vad_proto_goTypes,
		DependencyIndexes: file_vad_proto_depIdxs,
		EnumInfos:         file_vad_proto_enumTypes,
		MessageInfos:      file_vad_proto_msgTypes,
	}.Build()
	File_vad_proto = out.File
	file_vad_proto_goTypes = nil
	file_vad_proto_depIdxs = nil
}
