// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: vad.proto

package vadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceSegmentation_Detect_FullMethodName = "/vad.VoiceSegmentation/Detect"
)

// VoiceSegmentationClient is the client API for VoiceSegmentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VoiceSegmentation performs voice activity detection and speaker diarization
// on audio input using pyannote segmentation 3.0.
type VoiceSegmentationClient interface {
	// Detect processes raw audio and returns speaker-diarized segments.
	Detect(ctx context.Context, in *Audio, opts ...grpc.CallOption) (*Diarization, error)
}

type voiceSegmentationClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceSegmentationClient(cc grpc.ClientConnInterface) VoiceSegmentationClient {
	return &voiceSegmentationClient{cc}
}

func (c *voiceSegmentationClient) Detect(ctx context.Context, in *Audio, opts ...grpc.CallOption) (*Diarization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Diarization)
	err := c.cc.Invoke(ctx, VoiceSegmentation_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceSegmentationServer is the server API for VoiceSegmentation service.
// All implementations must embed UnimplementedVoiceSegmentationServer
// for forward compatibility.
//
// VoiceSegmentation performs voice activity detection and speaker diarization
// on audio input using pyannote segmentation 3.0.
type VoiceSegmentationServer interface {
	// Detect processes raw audio and returns speaker-diarized segments.
	Detect(context.Context, *Audio) (*Diarization, error)
	mustEmbedUnimplementedVoiceSegmentationServer()
}

// UnimplementedVoiceSegmentationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceSegmentationServer struct{}

func (UnimplementedVoiceSegmentationServer) Detect(context.Context, *Audio) (*Diarization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedVoiceSegmentationServer) mustEmbedUnimplementedVoiceSegmentationServer() {}
func (UnimplementedVoiceSegmentationServer) testEmbeddedByValue()                           {}

// UnsafeVoiceSegmentationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceSegmentationServer will
// result in compilation errors.
type UnsafeVoiceSegmentationServer interface {
	mustEmbedUnimplementedVoiceSegmentationServer()
}

func RegisterVoiceSegmentationServer(s grpc.ServiceRegistrar, srv VoiceSegmentationServer) {
	// If the following call pancis, it indicates UnimplementedVoiceSegmentationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceSegmentation_ServiceDesc, srv)
}

func _VoiceSegmentation_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Audio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceSegmentationServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceSegmentation_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceSegmentationServer).Detect(ctx, req.(*Audio))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceSegmentation_ServiceDesc is the grpc.ServiceDesc for VoiceSegmentation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceSegmentation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vad.VoiceSegmentation",
	HandlerType: (*VoiceSegmentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _VoiceSegmentation_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vad.proto",
}
