package vad

import (
	"encoding/binary"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sync"

	ort "github.com/yalue/onnxruntime_go"

	"github.com/accretional/vad/fbank"
)

// FireRedVAD model constants (from FireRedTeam/FireRedVAD VAD variant).
//
// Pure DFSMN over fbank features + CMVN. Output is one sigmoid prob per
// 10 ms frame (1 = speech). Non-streaming graph (FSMN lookahead means the
// model is NOT causal — see firered_test.go for the trade-offs around
// running this in sliding windows).
const (
	fireredInputMels       = 80
	fireredFrameStepMs     = 10
	fireredSmoothWindow    = 5 // frames; boxcar smoothing of sigmoid probs
	fireredSpeechThreshold = 0.4
	fireredMinSpeechFrames = 20 // 200 ms
	fireredMinSilenceFrames = 20 // 200 ms
	fireredBackfillFrames  = 5  // extend each silence→speech transition back this many frames
)

// FireRed is the FireRedTeam DFSMN-VAD backend. Implements Backend.
//
// Loads ONNX from `<weightsDir>/model.onnx` and CMVN from `cmvn_means.f32` +
// `cmvn_istd.f32` (raw float32 LE, 80 each). Generated by speax/benchmarks/vad/
// export_firered_vad_to_onnx.py from the upstream PyTorch checkpoint.
type FireRed struct {
	mu       sync.Mutex
	session  *ort.DynamicAdvancedSession
	fb       *fbank.Fbank
	means    []float32 // [80]
	istd     []float32 // [80] inverse std-dev (already inverted)
}

// NewFireRed creates a new FireRed VAD backend from a weights directory
// containing model.onnx, cmvn_means.f32, cmvn_istd.f32.
func NewFireRed(weightsDir string) (*FireRed, error) {
	modelPath := filepath.Join(weightsDir, "model.onnx")
	meansPath := filepath.Join(weightsDir, "cmvn_means.f32")
	istdPath := filepath.Join(weightsDir, "cmvn_istd.f32")

	means, err := readFloat32File(meansPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", meansPath, err)
	}
	istd, err := readFloat32File(istdPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", istdPath, err)
	}
	if len(means) != fireredInputMels || len(istd) != fireredInputMels {
		return nil, fmt.Errorf("cmvn dims: means=%d istd=%d, want %d each",
			len(means), len(istd), fireredInputMels)
	}

	fbOpts := fbank.Defaults() // Povey window, preemph 0.97 — matches FireRed pipeline
	fbOpts.NumMelBins = fireredInputMels
	fb, err := fbank.New(fbOpts)
	if err != nil {
		return nil, fmt.Errorf("build fbank: %w", err)
	}

	session, err := ort.NewDynamicAdvancedSession(
		modelPath, []string{"feat"}, []string{"probs"}, nil)
	if err != nil {
		return nil, fmt.Errorf("create firered session: %w", err)
	}

	return &FireRed{
		session: session,
		fb:      fb,
		means:   means,
		istd:    istd,
	}, nil
}

// Close releases all resources.
func (m *FireRed) Close() {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.session != nil {
		m.session.Destroy()
	}
}

// ProcessAudio runs FireRed VAD on raw 16 kHz mono float32 audio in [-1, 1].
func (m *FireRed) ProcessAudio(samples []float32) ([]Segment, error) {
	if len(samples) == 0 {
		return nil, nil
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	// Scale to int16 range. The FireRed front-end's kaldi-native-fbank wrapper
	// silently produces ~0 features for float32 [-1,1] input — same as FunASR.
	scaled := make([]float32, len(samples))
	for i, s := range samples {
		scaled[i] = s * 32768.0
	}

	feats := m.fb.Compute(scaled)
	if len(feats) == 0 {
		return nil, nil
	}
	t := len(feats)

	// CMVN: (x - mean) * istd
	flat := make([]float32, t*fireredInputMels)
	for i := 0; i < t; i++ {
		row := feats[i]
		for j := 0; j < fireredInputMels; j++ {
			flat[i*fireredInputMels+j] = (row[j] - m.means[j]) * m.istd[j]
		}
	}

	featShape := ort.NewShape(1, int64(t), int64(fireredInputMels))
	featIn, err := ort.NewTensor(featShape, flat)
	if err != nil {
		return nil, fmt.Errorf("create feat tensor: %w", err)
	}
	defer featIn.Destroy()

	probsShape := ort.NewShape(1, int64(t), 1)
	probsOut, err := ort.NewEmptyTensor[float32](probsShape)
	if err != nil {
		return nil, fmt.Errorf("create probs tensor: %w", err)
	}
	defer probsOut.Destroy()

	if err := m.session.Run([]ort.Value{featIn}, []ort.Value{probsOut}); err != nil {
		return nil, fmt.Errorf("firered inference: %w", err)
	}

	probs := probsOut.GetData()
	if len(probs) != t {
		return nil, fmt.Errorf("probs len %d != frames %d", len(probs), t)
	}
	return fireredExtractSegments(probs), nil
}

// fireredExtractSegments runs the 4-state postprocess derived from
// fireredvad/core/vad_postprocessor.py: boxcar smooth → threshold →
// {SILENCE, POSSIBLE_SPEECH, SPEECH, POSSIBLE_SILENCE} machine with
// hysteresis on speech/silence run lengths.
func fireredExtractSegments(probs []float32) []Segment {
	n := len(probs)
	if n == 0 {
		return nil
	}

	// 1. Boxcar smoothing (window length fireredSmoothWindow), cumulative mean
	//    for the first few frames matching the upstream behaviour.
	smoothed := make([]float32, n)
	for i := 0; i < n; i++ {
		lo := i - fireredSmoothWindow + 1
		if lo < 0 {
			lo = 0
		}
		var sum float32
		for j := lo; j <= i; j++ {
			sum += probs[j]
		}
		smoothed[i] = sum / float32(i-lo+1)
	}

	// 2. Per-frame raw labels.
	const (
		stateSilence         = 0
		statePossibleSpeech  = 1
		stateSpeech          = 2
		statePossibleSilence = 3
	)
	state := stateSilence
	var segments []Segment
	var transitionFrame int    // start of the current run in `state`
	var lastSpeechStart int = -1 // most recent speech-segment start (for backfill)
	var lastEndedSegEnd int    // for splitting long runs (not yet implemented; rare)

	flushSpeech := func(end int) {
		if lastSpeechStart >= 0 && end > lastSpeechStart {
			segments = append(segments, Segment{
				Start:      framesToSec(lastSpeechStart),
				End:        framesToSec(end),
				SpeakerID:  0,
				Confidence: 1.0,
			})
		}
		lastSpeechStart = -1
	}

	for i := 0; i < n; i++ {
		isSpeech := smoothed[i] >= float32(fireredSpeechThreshold)
		switch state {
		case stateSilence:
			if isSpeech {
				state = statePossibleSpeech
				transitionFrame = i
			}
		case statePossibleSpeech:
			if !isSpeech {
				state = stateSilence
			} else if i-transitionFrame+1 >= fireredMinSpeechFrames {
				state = stateSpeech
				// Backfill: extend segment start back fireredBackfillFrames.
				start := transitionFrame - fireredBackfillFrames
				if start < 0 {
					start = 0
				}
				// Make sure not to overlap with the last emitted segment.
				if start < lastEndedSegEnd {
					start = lastEndedSegEnd
				}
				lastSpeechStart = start
			}
		case stateSpeech:
			if !isSpeech {
				state = statePossibleSilence
				transitionFrame = i
			}
		case statePossibleSilence:
			if isSpeech {
				state = stateSpeech
			} else if i-transitionFrame+1 >= fireredMinSilenceFrames {
				state = stateSilence
				end := transitionFrame
				flushSpeech(end)
				lastEndedSegEnd = end
			}
		}
	}

	// Flush any open speech run at end of stream.
	if state == stateSpeech || state == statePossibleSilence {
		flushSpeech(n)
	}
	return segments
}

// readFloat32File reads a raw little-endian float32 file into a []float32.
func readFloat32File(path string) ([]float32, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(raw)%4 != 0 {
		return nil, fmt.Errorf("%s: %d bytes not a multiple of 4", path, len(raw))
	}
	n := len(raw) / 4
	out := make([]float32, n)
	for i := 0; i < n; i++ {
		out[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[i*4:]))
	}
	return out, nil
}

// compile-time check.
var _ Backend = (*FireRed)(nil)
